# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# sys.path path, space-separated, to be prepended to sys.path before loading env.py
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# version path separator; defaults to os.pathsep.
# version_path_separator = :

# version locations.
version_locations = %(here)s/alembic/versions

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
