import os
import logging
from typing import Dict, Any, Optional, List
from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfgen import canvas

from app.config import settings
from app.models.user import User
from app.models.report import Report
from app.utils.medical_utils import medical_engine

logger = logging.getLogger(__name__)

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically calculate the total page count
    and draw consistent headers and footers on all pages.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        
        # Color definitions
        primary_color = colors.HexColor("#1e3a8a") # Deep Slate Blue
        text_muted = colors.HexColor("#64748b") # Cool Grey
        
        # Draw Header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(primary_color)
        self.drawString(54, 750, "HEALTHINSIGHT AI — PATIENT MEDICAL REPORT ANALYSIS")
        
        # Header separator line
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Draw Footer
        self.line(54, 50, 558, 50)
        self.setFont("Helvetica", 8)
        self.setFillColor(text_muted)
        self.drawString(54, 38, "Confidential Document — Generated by HealthInsight AI Platform.")
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 38, page_str)
        
        self.restoreState()


class PDFService:
    def generate_report_pdf(
        self,
        user: User,
        report: Report,
        comparison: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Creates a structured, beautifully stylized medical analysis PDF report using ReportLab.
        Returns the PDF as raw bytes.
        """
        logger.info(f"Generating PDF for report ID: {report.id}")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1e3a8a"),
            spaceAfter=15
        )
        
        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#1e3a8a"),
            spaceBefore=12,
            spaceAfter=8,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'BodyDark',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155")
        )
        
        body_bold = ParagraphStyle(
            'BodyBold',
            parent=body_style,
            fontName='Helvetica-Bold'
        )
        
        callout_style = ParagraphStyle(
            'CalloutText',
            parent=body_style,
            fontSize=10.5,
            leading=15,
            textColor=colors.HexColor("#0f172a")
        )

        story = []
        
        # 1. Header Section / Title
        story.append(Paragraph("AI-Powered Clinical Analysis Report", title_style))
        story.append(Spacer(1, 0.1 * inch))
        
        # 2. Patient Demographics & Report Meta Info (Table)
        meta_data = [
            [
                Paragraph("<b>Patient Name:</b>", body_style),
                Paragraph(user.full_name, body_style),
                Paragraph("<b>Report Date:</b>", body_style),
                Paragraph(report.created_at.strftime('%Y-%m-%d %H:%M'), body_style)
            ],
            [
                Paragraph("<b>Age / Gender:</b>", body_style),
                Paragraph(f"{report.medical_values.age or user.age or 'N/A'} Yrs / {report.medical_values.gender or user.gender or 'N/A'}", body_style),
                Paragraph("<b>Report Status:</b>", body_style),
                Paragraph(report.status, body_style)
            ],
            [
                Paragraph("<b>File Name:</b>", body_style),
                Paragraph(report.file_name, body_style),
                Paragraph("<b>Health Score:</b>", body_bold),
                Paragraph(f"<b>{report.prediction.health_score if report.prediction else 'N/A'} / 100</b>", body_bold)
            ]
        ]
        
        meta_table = Table(meta_data, colWidths=[1.25*inch, 2.0*inch, 1.25*inch, 2.5*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 8),
            ('LINEBELOW', (0,-1), (-1,-1), 1, colors.HexColor("#cbd5e1")),
            ('LINEABOVE', (0,0), (-1,0), 1, colors.HexColor("#cbd5e1")),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.2 * inch))
        
        # 3. AI Executive Summary (Callout box)
        if report.ai_summary:
            story.append(Paragraph("AI Executive Summary", h1_style))
            summary_data = [[Paragraph(report.ai_summary, callout_style)]]
            summary_table = Table(summary_data, colWidths=[7.0*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#eff6ff")), # light blue
                ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#bfdbfe")),
                ('PADDING', (0,0), (-1,-1), 12),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            story.append(summary_table)
            story.append(Spacer(1, 0.2 * inch))

        # 4. ML Risk Predictions
        if report.prediction:
            story.append(Paragraph("Predictive Disease Risk Assessment (ML Engine)", h1_style))
            pred = report.prediction
            
            # Map risk colors for visual warning indicator
            def get_risk_style(risk_level: str) -> ParagraphStyle:
                color_map = {
                    "HIGH": "#ef4444",      # Red
                    "BORDERLINE": "#f59e0b",# Amber
                    "LOW": "#10b981"         # Green
                }
                hex_color = color_map.get(risk_level.upper(), "#334155")
                return ParagraphStyle(
                    f"Risk_{risk_level}",
                    parent=body_bold,
                    textColor=colors.HexColor(hex_color)
                )

            risk_data = [
                [
                    Paragraph("<b>Condition / Disease</b>", body_bold),
                    Paragraph("<b>Risk Prediction Level</b>", body_bold),
                    Paragraph("<b>Clinical Relevance</b>", body_bold)
                ],
                [
                    Paragraph("Heart Disease Risk", body_style),
                    Paragraph(pred.heart_disease_risk, get_risk_style(pred.heart_disease_risk)),
                    Paragraph("Estimated risk based on blood lipids, blood pressure, and age.", body_style)
                ],
                [
                    Paragraph("Diabetes Risk", body_style),
                    Paragraph(pred.diabetes_risk, get_risk_style(pred.diabetes_risk)),
                    Paragraph("Estimated risk of glycemic dysregulation (HbA1c & Blood Sugar).", body_style)
                ],
                [
                    Paragraph("Kidney Disease Risk", body_style),
                    Paragraph(pred.kidney_disease_risk, get_risk_style(pred.kidney_disease_risk)),
                    Paragraph("Based on serum creatinine and glomerular filtration indicators.", body_style)
                ],
                [
                    Paragraph("Stroke Risk", body_style),
                    Paragraph(pred.stroke_risk, get_risk_style(pred.stroke_risk)),
                    Paragraph("Based on blood pressure levels and cardiovascular variables.", body_style)
                ]
            ]
            
            risk_table = Table(risk_data, colWidths=[2.0*inch, 1.5*inch, 3.5*inch])
            risk_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                ('PADDING', (0,0), (-1,-1), 8),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story.append(risk_table)
            story.append(Spacer(1, 0.25 * inch))

        # 5. Extracted Biomarker Ranges
        story.append(Paragraph("Biomarkers & Medical Parameters Analysis", h1_style))
        biomarker_headers = [
            Paragraph("<b>Parameter</b>", body_bold),
            Paragraph("<b>Extracted Value</b>", body_bold),
            Paragraph("<b>Reference Range</b>", body_bold),
            Paragraph("<b>Status</b>", body_bold)
        ]
        
        biomarker_rows = [biomarker_headers]
        
        abnormal_parameters = []
        
        mv = report.medical_values
        if mv:
            # Map of database keys to JSON keys
            keys_mapping = [
                ("blood_sugar", "blood_sugar"),
                ("hba1c", "hba1c"),
                ("systolic_bp", "systolic_bp"),
                ("diastolic_bp", "diastolic_bp"),
                ("heart_rate", "heart_rate"),
                ("spo2", "spo2"),
                ("hdl", "hdl"),
                ("ldl", "ldl"),
                ("triglycerides", "triglycerides"),
                ("total_cholesterol", "total_cholesterol"),
                ("creatinine", "creatinine"),
                ("hemoglobin", "hemoglobin"),
                ("weight", "weight"),
                ("bmi", "bmi")
            ]
            
            for db_key, json_key in keys_mapping:
                val = getattr(mv, db_key, None)
                if val is not None:
                    # BP joint classification is handled differently in the engine, but values are displayed
                    details = medical_engine.get_parameter_details(json_key, val)
                    status = details["status"]
                    unit = details["unit"]
                    name = details["name"]
                    
                    # Reference string construction
                    param_ref = medical_engine.reference_data.get(json_key, {})
                    normal_range = param_ref.get("ranges", {}).get("normal", {})
                    ref_str = "N/A"
                    if "min" in normal_range and "max" in normal_range:
                        ref_str = f"{normal_range['min']} - {normal_range['max']} {unit}"
                    elif "min" in normal_range:
                        ref_str = f"≥ {normal_range['min']} {unit}"
                    elif "max" in normal_range:
                        ref_str = f"≤ {normal_range['max']} {unit}"

                    # Status styling
                    status_color = "#334155" # Grey
                    if status in ("HIGH", "LOW"):
                        status_color = "#ef4444" # Red
                        abnormal_parameters.append(details)
                    elif status == "BORDERLINE":
                        status_color = "#f59e0b" # Amber
                        abnormal_parameters.append(details)
                    elif status == "NORMAL":
                        status_color = "#10b981" # Green
                        
                    status_style = ParagraphStyle(
                        f"MV_Status_{db_key}", parent=body_bold, textColor=colors.HexColor(status_color)
                    )
                    
                    biomarker_rows.append([
                        Paragraph(name, body_style),
                        Paragraph(f"{val} {unit}", body_style),
                        Paragraph(ref_str, body_style),
                        Paragraph(status, status_style)
                    ])

            # Special joint Blood Pressure evaluation row
            if mv.systolic_bp is not None and mv.diastolic_bp is not None:
                bp_eval = medical_engine.evaluate_blood_pressure(mv.systolic_bp, mv.diastolic_bp)
                bp_status = bp_eval["status"]
                
                bp_color = "#10b981"
                if "HIGH" in bp_status:
                    bp_color = "#ef4444"
                elif "BORDERLINE" in bp_status:
                    bp_color = "#f59e0b"
                    
                bp_status_style = ParagraphStyle(
                    "BP_Status_Joint", parent=body_bold, textColor=colors.HexColor(bp_color)
                )
                
                biomarker_rows.append([
                    Paragraph("<b>Blood Pressure (Joint)</b>", body_style),
                    Paragraph(f"{mv.systolic_bp}/{mv.diastolic_bp} mmHg", body_bold),
                    Paragraph("120 / 80 mmHg", body_style),
                    Paragraph(bp_status, bp_status_style)
                ])

            bio_table = Table(biomarker_rows, colWidths=[2.2*inch, 1.5*inch, 2.0*inch, 1.3*inch])
            bio_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story.append(bio_table)
            story.append(Spacer(1, 0.2 * inch))

        # Page break before abnormal breakdown & lifestyle if table was long
        story.append(PageBreak())

        # 6. Breakdown of Abnormal Parameters (Warning Callouts)
        if abnormal_parameters:
            story.append(Paragraph("Clinical Breakdown of Out-of-Range Parameters", h1_style))
            for details in abnormal_parameters:
                name = details["name"]
                val = details["value"]
                unit = details["unit"]
                status = details["status"]
                risk = details["risk"]
                suggestion = details["lifestyle_suggestion"]
                doctor = details["doctor_advice"]
                
                callout_color = "#fef3c7" if status == "BORDERLINE" else "#fee2e2"
                border_color = "#f59e0b" if status == "BORDERLINE" else "#ef4444"
                
                param_story = [
                    Paragraph(f"<b>{name}</b> — Value: <b>{val} {unit}</b> ({status})", body_bold),
                    Paragraph(f"<b>Meaning:</b> {details['meaning']}", body_style),
                    Paragraph(f"<b>Risks:</b> {risk}", body_style),
                    Paragraph(f"<b>Lifestyle Recommendations:</b> {suggestion}", body_style),
                    Paragraph(f"<b>Clinical Advice:</b> {doctor}", body_style),
                ]
                
                # Wrap parameter details in a beautiful table
                param_table = Table([[param_story]], colWidths=[7.0*inch])
                param_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(callout_color)),
                    ('BOX', (0,0), (-1,-1), 1, colors.HexColor(border_color)),
                    ('PADDING', (0,0), (-1,-1), 10),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ]))
                story.append(param_table)
                story.append(Spacer(1, 0.12 * inch))
            story.append(Spacer(1, 0.1 * inch))

        # 7. Comparison History Details (if provided)
        if comparison:
            story.append(Paragraph("Progress Tracking & Comparison Results", h1_style))
            
            comp_data = comparison.get("comparison_data", {})
            improvement_pct = comparison.get("overall_improvement_percentage", 0.0)
            comp_summary = comparison.get("ai_summary", "")

            # Print comparison meta
            story.append(Paragraph(
                f"Overall progress indicator between baseline and current report: "
                f"<b>{improvement_pct:+.2f}% Improvement</b>.", body_bold
            ))
            
            if comp_summary:
                story.append(Paragraph(f"<b>Progress Summary:</b> {comp_summary}", body_style))
                story.append(Spacer(1, 0.1 * inch))
                
            comp_rows = [[
                Paragraph("<b>Biomarker</b>", body_bold),
                Paragraph("<b>Previous Value</b>", body_bold),
                Paragraph("<b>Current Value</b>", body_bold),
                Paragraph("<b>Difference</b>", body_bold),
                Paragraph("<b>Progress Status</b>", body_bold)
            ]]
            
            for key, val in comp_data.items():
                p_name = val["parameter"]
                prev_v = val["previous_value"]
                curr_v = val["current_value"]
                diff_v = val["difference"]
                status = val["status"]
                unit = val["unit"]
                
                # Custom bp formatting
                if key == "blood_pressure":
                    prev_val_str = val.get("previous_str", f"{prev_v}")
                    curr_val_str = val.get("current_str", f"{curr_v}")
                    diff_val_str = f"Distance Shift: {diff_v:+.1f}"
                else:
                    prev_val_str = f"{prev_v} {unit}" if prev_v is not None else "N/A"
                    curr_val_str = f"{curr_v} {unit}" if curr_v is not None else "N/A"
                    diff_val_str = f"{diff_v:+.2f} {unit}" if diff_v is not None else "N/A"

                status_color = "#334155"
                if status == "Improved":
                    status_color = "#10b981"
                elif status == "Worsened":
                    status_color = "#ef4444"
                elif status == "Stable":
                    status_color = "#f59e0b"
                    
                status_style = ParagraphStyle(
                    f"Comp_Status_{key}", parent=body_bold, textColor=colors.HexColor(status_color)
                )

                comp_rows.append([
                    Paragraph(p_name, body_style),
                    Paragraph(prev_val_str, body_style),
                    Paragraph(curr_val_str, body_bold),
                    Paragraph(diff_val_str, body_style),
                    Paragraph(status, status_style)
                ])

            comp_table = Table(comp_rows, colWidths=[2.0*inch, 1.25*inch, 1.25*inch, 1.25*inch, 1.25*inch])
            comp_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f8fafc")),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                ('PADDING', (0,0), (-1,-1), 6),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ]))
            story.append(comp_table)
            story.append(Spacer(1, 0.25 * inch))

        # Build PDF using our NumberedCanvas class
        doc.build(story, canvasmaker=NumberedCanvas)
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        # Save to generated_reports local folder
        try:
            reports_path = settings.reports_path / str(user.id)
            reports_path.mkdir(parents=True, exist_ok=True)
            saved_path = reports_path / f"report_{report.id}.pdf"
            with open(saved_path, "wb") as f:
                f.write(pdf_bytes)
            # Update path on db model to point to generated PDF
            report.file_path = str(saved_path)
            logger.info(f"Successfully saved PDF report at: {saved_path}")
        except Exception as e:
            logger.error(f"Failed to save generated PDF to disk: {e}")

        return pdf_bytes

pdf_service = PDFService()
